### PR TITLE
Suru Icon for Ubuntu

### PR DESCRIPTION
**Pull request by FabianOvrWrt**

### CODE REVIEW

**Comment by nfsprodriver** [comment]
I love it!!!

**Comment by FabianOvrWrt** [comment]
Thank you! I can upload the original SVG if you want it.

**Comment by nfsprodriver** [comment]
Yes, you can post it here. I think about, when we should change the icon. Maybe, when we implemented noise or another big feature. We should discuss this in the telegram group...

**Comment by nfsprodriver** [comment]
Merged into android branch. Looks great! Thank you.

**Pull request closed without merging**
