### PR TITLE
Index fixes

### PR DESCRIPTION
**Pull request by FabianOvrWrt**
This fixes some spacing issues with the ticks (they are cut out) and a height issue, where the Info tab text is not fully visible on small screens.

This was tested on Alcatel One Touch Fire C (Firefox OS 1.3) and One Touch Fire (Firefox 1.4 - 2.1) and I don't know if this creates another problem in other phones.

### CODE REVIEW

**Comment by TitanNano** [comment]
no, they are not cut off. 
It's a gecko rendering bug. I already tested it on my Peak cause I had the same problem.

But I'll test this patch later an see if it changes something.

**Comment by FabianOvrWrt** [comment]
I don't know if the problem with the ticks is just for these phones, I saw it on the Fire C and I though that it was just a problem with Firefox OS 1.3, but I've tested Loqui on every Firefox OS version possible on the One Touch Fire and I get the same problem.

You may not be able to reproduce the Info tab text issue because the text itself should fit without scrolling on the Peak, since it has a larger screen, this just fixes the problem with HVGA screen phones.

**Comment by TitanNano** [comment]
Hmmm, on my peak the second tick is also cut off until the next re render.
I played around with the spacing and it didn't change anything. But I'll
see if your patch changes anything for me...

2015-02-17 17:15 GMT+01:00 Fabián PS notifications@github.com:

**Comment by gargsms** [comment]
I can confirm that the ticks are not getting placed at the proper place in Flame with Firefox OS v2.

**Comment by TitanNano** [comment]
hmm okay I'll test the patch now.

2015-02-17 20:45 GMT+01:00 Sukant Garg notifications@github.com:

**Comment by TitanNano** [comment]
I couldn't see any difference on my device.

**Pull request merged**
