### PR TITLE
storage locks

### PR DESCRIPTION
**Pull request by TitanNano**
this introduces read / write locks for the storage chunks. It will prevent the app from accidentally overwriting chunk updates.

### CODE REVIEW

**Comment by cmeerw** [comment]
That doesn't seem to be working for me... It currently seems to ignore any incoming messages...

**Comment by cmeerw** [comment]
I am getting:

`TypeError: values[1] is undefined (message.js:63:12)`

**Comment by TitanNano** [comment]
it's working for me :/. I just got a message on whatsapp.
I will fix the typo.

**Comment by TitanNano** [comment]
what you can do is check `Store.locks` and check if there are some still locked chunks.

**Comment by TitanNano** [comment]
I see. I fix that. thanks :+1:

**Comment by cmeerw** [comment]
It seems to work now after changing "values[1].chunkIndex" to "values.result.chunkIndex" in message.js:63

**Comment by TitanNano** [comment]
okay alright, I did that too. I will make a PR.

**Pull request merged**
