### PR TITLE
Limit avatars render to current account

### PR DESCRIPTION
**Pull request by cmeerw**

### CODE REVIEW

**Comment by TitanNano** [comment]
the profile section avatar image is also not rendered anymore. I think you should add this too...

**Comment by cmeerw** [comment]
Sorry, which one do you mean? Is there any avatar still missing with the latest commit?

**Comment by cmeerw** [comment]
Ah ok, seeing it now (but only for XMPP)...

**Comment by TitanNano** [comment]
no WhatsApp too. open "aside menu" > select "gear", no avatar is rendered, for XMPP and WhatsApp. It should be `section#me`

**Comment by cmeerw** [comment]
Sorry, still don't get that one... Are both ("aside" and "section#me") missing for you or just one of them (because they should be rendered at the same time)?
Do you have an entry in App.avatars for it?

**Comment by TitanNano** [comment]
both are missing and I had them before your patch.

**Comment by cmeerw** [comment]
I don't understand that - it should get rendered by account.js line 487 (unless it somehow isn't available in App.avatars any more (but nothing there should have changed)). So I am a bit lost now as it does get rendered for me and I don't know why it wouldn't for you.

**Comment by TitanNano** [comment]
okay, I applied all your latest patches and now everything is working.

**Pull request merged**
