### PR TITLE
Update coseme.js

### PR DESCRIPTION
**Pull request by justapps4all**
Patch to avoid banning accounts in WhatsApp network when a user use other App compatible with WhatsApp or other device, with the same mobile number

### CODE REVIEW

**Comment by justapps4all** [comment]
Patch to avoid banning accounts in WhatsApp network when a user use other App compatible with WhatsApp or other device, with the same mobile number

**Comment by Gioyik** [comment]
r? -----> @aesedepece

**Comment by aesedepece** [comment]
Can't see the diff. What are the changes? Thanks!

**Comment by justapps4all** [comment]
Sorry, I think there is an error with GitHub editor. These are the changes (3 new blocks):

```
auth_login: function(aUsername, aPassword) {
    logger.log('auth_login called for', aUsername);
```

//NEW
        if(localStorage.flagAuthFail===true){
                //TODO shows message: your are using WhatsApp in other device or App  
        }else{
//END-NEW
         CoSeMe.auth.authenticate(aUsername, aPassword, function(aConn) {
         try {
         if (aConn) {
         self.socket = aConn;
         self.readerThread.socket = self.socket;
         self.readerThread.autoPong = self.autoPong;
         self.readerThread.ping = self.sendPing;
         self.readerThread.onPing = self.sendPong;
         self.readerThread.signalInterface = {
         send: fireEvent
         };
         self.jid = self.socket.jid;
         self.out = self.socket.writer;
         self.state = 2;
         self.domain = CoSeMe.config.auth.domain;
         fireEvent('auth_success', [aUsername, null]);
         } else {
         fireEvent('auth_fail', [aUsername, null]);
         //patch what avoid banning accounts in WhatApp Network
//NEW
         localStorage.flagAuthFail=true;
//END-NEW
         }
         } catch (x) {
         logger.error('Error authenticating!', x);
         self.state = 0;
         fireEvent('auth_fail', [aUsername, null]);
         }
         });
//NEW
        }
//END-NEW
    },

**Comment by aesedepece** [comment]
CoSeMe it's a different project (the LoquiIM community didn't code it), I'm not in favour of modifying it from LoquiIM. 

So... the flag should not be set in the library but in the app at `function SI.registerListener @ function this.connect @ /scripts/connectors/coseme.js`.

Anyway, I think the right way to go is to open an issue with something like "Login can't tell if WA password is no longer valid", and discuss there what's the more elegant/proper solution from the UX side.

What do you reckon?

**Comment by justapps4all** [comment]
I agree. But please take in account that this is only a patch for Loqui v2.3. If you can implement in a better way before deploying the version 2.3, good. But at the moment, we are receiving emails from users who get their phone numbers banned in the WhatsApp network, after using Loqui v2.2

Count on our support on this.

**Comment by Gioyik** [comment]
We are receiving? Who?

**Comment by aesedepece** [comment]
@Gioyik At first, I though it was someone from WhatsApp Inc., but then realized that @devja4a means JustApps4All. I'm very happy to see them in here :)

**Comment by Gioyik** [comment]
@devja4a The problem with blocked accounts is that users install ConnectA2 and Loqui at the same time, they request the confirmation code in Loqui and ConnectA2 at the same time, and the register their phone in Loqui and ConnectA2 at the same time in the same device. At the other day they repeat the process of the last day. Sometimes people is a little (a lot) crazy to get Whatsapp on FirefoxOS devices. Thanks for the pull request, we really appreciate.

@aesedepece every day this it's so close to convert in a romance soap opera story. Whatsapp is the ambitious and evil aunt :P

**Pull request closed without merging**
