### PR TITLE
improve-emoji-handling

### PR DESCRIPTION
**Pull request by Honk2**
- improved integration of the emoji keyboard
  - simulated keydown
  - no more need to switch keybord before sending
- layout change for better handling

### CODE REVIEW

**Comment by cmeerw** [comment]
hmmm... that conflicts with one of the other PRs now...

Anyway, just noticed that there still is another strange interaction between WhatsApp and XMPP emojis: go to an XMPP chat and open the emojis, then go to a WhatsApp chat and open the WhatsApp emojis and you now get both sets of emojis displayed...

**Comment by Honk2** [comment]
@cmeerw rw ok I will check this

**Comment by Honk2** [comment]
@cmeerw I think I resolved the conflicts and also fixed the emoji mix up

**Comment by Honk2** [comment]
The last commit was neccessary to comply with #1017

**Comment by cmeerw** [comment]
Closing a chat via tapping on the left arrow in the top left corner now activates the keyboard which is very strange.

When emoji mode is active you can now only go back via tapping the keyboard icon, but not by tapping on the text field or somewhere in the chat window which seems strange to me. Is this intentional?

**Comment by Honk2** [comment]
Argh! This behaviour (the back arrow) was not intended and work in a intermediate version, but probaply I messed it up with one of the previous cross commits..I will correct it.

Changing from the emoji to the regular keyboard by the keyboard iocn only is intended. My thinking is,
- you can now scroll while typing emojis
- you can send a message with the emoji keyboard open
- cannot accidently close the emoji keyboard.
  The new behaviour seems more intuitive to me. Tapping the chat window to open the keyboard dosnt make sense to me. I will add an tap event to the text field for changing the keyboard.

**Pull request merged**
