### PR TITLE
Revert "Supports multiline messages now" #668 

### PR DESCRIPTION
**Pull request by TitanNano**
sorry, does not work with the virtual FxOS keyboard :/ we need a better solution.

### CODE REVIEW

**Comment by gargsms** [comment]
What exactly were the problems?
I have tested it on the Simulators. And the physical device running latest 3.0.0 nightly.

**Comment by TitanNano** [comment]
on my peak with v2.1
e.key was always "unidentified" and e.shiftKey was never true, even when I
enabled it :/

2015-04-02 8:58 GMT+02:00 Sukant Garg notifications@github.com:

**Comment by gargsms** [comment]
Oh, I see. The support is not available before Gecko 23.  You would need to update gecko.

The e.which is marked as deprecated anyway. So we would need to merge it later when we are sure everyone is using v2.2+, which we are never gonna be sure about. :-|

**Comment by TitanNano** [comment]
well v2.1 runs with gecko 34, I don't know whats the problem. We should
support at least 1.4 so you could check if key is available or not. For the
multiline feature, maybe you add a "send with enter key" option in the
settings? Most messengers do it like this, and as long as shiftKey does not
work, I think that would be the best way.

2015-04-02 10:41 GMT+02:00 Sukant Garg notifications@github.com:

**Comment by gargsms** [comment]
Seems to be a fine idea. I will add it as an option.
Also, I was thinking of adding the long tap (contextmenu) for copy as an option because v3.0 supports Copy Paste and it is annoying when there are two things for one action. I will push it later this day (and not merge it directly.) You can then test it. :)

```
 On Thursday, 2 April 2015 2:20 PM, Jovan Gerodetti <notifications@github.com> wrote:
```

 well v2.1 runs with gecko 34, I don't know whats the problem. We should
support at least 1.4 so you could check if key is available or not. For the
multiline feature, maybe you add a "send with enter key" option in the
settings? Most messengers do it like this, and as long as shiftKey does not
work, I think that would be the best way.

2015-04-02 10:41 GMT+02:00 Sukant Garg notifications@github.com:

**Comment by TitanNano** [comment]
well you are going to add the single message deletion feature? we could
need some kind of edit mode for that... maybe we could move the message
forwarding also to this edit mode.

2015-04-02 10:58 GMT+02:00 Sukant Garg notifications@github.com:

> Seems to be a fine idea. I will add it as an option.
> Also, I was thinking of adding the long tap (contextmenu) for copy as an
> option because v3.0 supports Copy Paste and it is annoying when there are
> two things for one action. I will push it later this day (and not merge it
> directly.) You can then test it. :)
> 
> On Thursday, 2 April 2015 2:20 PM, Jovan Gerodetti <

**Pull request merged**
