### PR TITLE
updated WhatsApp token data

### PR DESCRIPTION
**Pull request by cmeerw**
see https://coderus.openrepos.net/whitesoft/whatsapp_scratch
related to #758 and #765

### CODE REVIEW

**Comment by TitanNano** [comment]
thank you, please do a CoSeMe PR too

**Comment by Hywan** [comment]
Has it been published on MarketPlace yet?

**Comment by TitanNano** [comment]
no

2015-07-17 13:44 GMT+02:00 Ivan Enderlin notifications@github.com:

**Comment by cmeerw** [comment]
Who can publish it on the Marketplace? Is it just @aesedepece ?

**Comment by TitanNano** [comment]
yes

**Comment by 03927e9c** [comment]
Ok so how much time are we gonna have to wait until this guy decides to publish it on Market Place? Months? A year? It's stupid to have just one guy that can do that, they should let others contributors do it, specially the one that are active.

**Comment by TitanNano** [comment]
yes good point, but right now he is the only one who has access. We need to wait for him to respond

**Comment by 03927e9c** [comment]
Is there any other way to contact him beside the petty mention on here? E-mail? Facebook?

**Comment by TitanNano** [comment]
I can sent a mail to the mailing list, but there has never been any activity jet.

**Comment by 03927e9c** [comment]
I mean a personal e-mail account or Facebook.

**Comment by TitanNano** [comment]
I sent him an personal email just now.

**Comment by aesedepece** [comment]
Later today I'll push the update and authorize others to do so.

I am really sorry I can't be in charge of this project any more for personal and work reasons.

Best regards,
Adán

**Comment by 03927e9c** [comment]
Appreciated!

**Comment by TitanNano** [comment]
:+1:

**Pull request merged**
