### PR TITLE
Add more groupinfo #901

### PR DESCRIPTION
**Pull request by Honk2**
I added to the WhatsApp Group Info the creation date and the subject change time.
In the participants list,
- Admins are indicated by a symbol
- the subject owner is indicated by a T
- the group creator is indicated by a star

### CODE REVIEW

**Comment by cmeerw** [comment]
I haven't tried it, but it looks like this could affect (i.e. break) XMPP?

**Comment by Honk2** [comment]
If there are groups possible in XMPP you are right.
Are there Groups possible in XMPP? If yes, the change in src/scripts/mozillahispano/coseme.js line 7305 must be applied to XMPP. Any XMPP tag must also be included in messenger.js

I know noone who is using XMPP thus I cannot test.

**Comment by Honk2** [comment]
@cmeerw could you please provide a grouInfo aquivalent for XMPP? Than I could at least make the required changes.

**Comment by Honk2** [comment]
@cmeerw I just lerned a lot about XMPP.
I will make the neccessary changes to XMPP and make commits to this PR when done.

**Comment by Honk2** [comment]
@cmeerw Now the extended group info is working with WhatsApp and XMPP

**Pull request merged**
