### PR TITLE
New version fix

### LINKED ISSUE #568: Adding Whatsapp account  could not send SMS
When trying to add my Indian number as a WhatsApp acount, I get an error saying that the SMS could not been sent. I opened the console and no much information is shown.

I regularly use the same number in a different phone with WhatsApp.

### PR DESCRIPTION
**Pull request by gargsms**
This solves the problems encountered by people in sending SMS.

Fixes : #568 and #565 

Source: https://github.com/perezdidac/WhatsAPINet/pull/226

### CODE REVIEW

**Comment by bdcomp** [comment]
This pull request includes many old changes from your pr #547.

Please use different branches for every issue/pr.

**Comment by gargsms** [comment]
I am sorry for that.

Do I need to revert back the changes, or will it be acceptable this time? Please. :stuck_out_tongue:

**Comment by bdcomp** [comment]
@aesedepece ?

**Comment by gargsms** [comment]
If he were here, the earlier commits would have got merged already.

**Comment by gargsms** [comment]
@bdcomp Why are two different PRs getting merged into one?
#547 was made on the dev branch of my repo, which is bad (I should have made a new branch for that.)
And this #570 is made on the New-Version branch in my repo.
Since both the PRs are on different branches, shouldn't they be shown in separate pages?

**Comment by bdcomp** [comment]
You probably created the New-Version branch from your dev branch, after the original changes.

**Comment by gargsms** [comment]
I made the earlier commits in my dev branch for which I am sorry.
But this time, I made the New-Version branch first, then made the changes, and then committed them.
I then created a new PR, which actually has a different number. I just don't understand why all the commits are shown in this.

Anyway, when are you merging it? I mailed @aesedepece a few times, he never responded.

**Comment by aarizkuren** [comment]
Hi, 
if you see the git log of New-Version, you can see that you have clone from your latest "dev" branch commit, not loqui's "dev" branch. https://github.com/gargsms/im/commits/New-Version
<code bash>
git checkout -b your_branch_name 0d3efda9c5d86b2f9923b990fc2181ac618fe20d
</code>
apply in that branch the changes and then do PR

I think this PR has many issues and its not easy no check it correctly.

**Comment by gargsms** [comment]
@aarizkuren Can you delete this and the earlier #547? I am making fresh PRs now using new branches for each feature or issue.

**Comment by aarizkuren** [comment]
:+1:

**Review by marangphl — COMMENTED** [review]
I want the new version of loqui im

**Pull request closed without merging**
