### PR TITLE
Reconnect on socket error

### PR DESCRIPTION
**Pull request by aesedepece**
EPIC: This fixes virtually every reported case of WhatsApp accounts constantly disconnecting.
This means that the reconnect button _should not_ be necessary any more...

### CODE REVIEW

**Comment by Gioyik** [comment]
Not necessary for other accounts too (like Jabber, Facebook... etc)?

**Comment by aesedepece** [comment]
No, the BOSH sessions survive to socket errors, short network outages and IP changes. That's why we still use it ;)

**Comment by Gioyik** [comment]
Sometimes Loqui doesn't shows that I receive a message, image.. etc since I use the reconnect button, after use it I receive the notification of a new message, this PR could solve the problem?

**Comment by aesedepece** [comment]
Yes, it should.

**Comment by Gioyik** [comment]
Working for me

**Pull request merged**
