### PR TITLE
fixes: reference error with provider longName used in the alt attribute ...

### PR DESCRIPTION
**Pull request by soapdog**
This basically a fix for a typo in the providers source code. There is an img tag that is supposed to receive the provider long name in its alt attribute but the variable has a typo in it. It reads "longName" instead of "data.longName" silly thing but such an easy fix and it is one less error on the console.

### CODE REVIEW

**Comment by Gioyik** [comment]
Thanks

**Comment by soapdog** [comment]
You're welcome Gio! :+1: 
I will improve my pull requests from now on...

**Comment by Gioyik** [comment]
Thanks. We are working on the v0.3.0 and there are a lot of work to do. So, everybody could help us with any issue from the milestone. We will appreciate it. :)

**Comment by soapdog** [comment]
How do I see the milestone issues?

**Comment by Gioyik** [comment]
https://github.com/loqui/im/issues?milestone=9&state=open

**Pull request merged**
