### PR TITLE
add a pulse for whatsapp accounts #359

### PR DESCRIPTION
**Pull request by TitanNano**
This adds an interval that sends presence requests for every chat every 30 seconds to keep the connection to whatsapp alive.
I tested it on my Geeksphone Peak and I can say that I wasn't disconnected the entire day. I was most of the time on wifi and the battery usage didn't increased, but I'll do future tests on mobile data, just to make sure.

### CODE REVIEW

**Comment by aesedepece** [comment]
Instead of requesting presence for every contact, you should:
- Map the contacts list to a phone numbers array
- Request presence for the whole list

This way you'll only send and recive one stanza instead of hundreds.

**Comment by TitanNano** [comment]
Oh thank you for that information, I'll change it.

**Comment by aesedepece** [comment]
Thanks a lot :)

**Comment by TitanNano** [comment]
okay, I changed it to one single request now.

**Pull request merged**
