### PR TITLE
implemented sending and receiving of vCards

### PR DESCRIPTION
**Pull request by cmeerw**
any user-interface tweaks are welcome...

### CODE REVIEW

**Comment by TitanNano** [comment]
looks good :+1:

**Comment by tibtab** [comment]
When I send a contact, I can only send one number and no other details :/
But I can receive detailed vcards.
Sometimes the vcard does not open immediately, for these cases in the webIDE I get `TypeError: img is null`

**Comment by cmeerw** [comment]
@tibtab what Firefox OS version are you using - I believe that's a limitation of older Firefox OS versions that only the number is exported from the Contacts app.
I noticed the "img is null" as well - it's not specific to vcards, but you can get that error with other media types as well (when you don't click on the icon itself).

**Comment by cmeerw** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Activities says "In Firefox OS 2.0+ we added a field that if you use webcontacts/contact you can get the whole contact:"

**Comment by tibtab** [comment]
I'm using 2.2.0.0-prerelease

**Comment by cmeerw** [comment]
That's strange, at least in the 2.2 simulator I get the whole contact info exported...

**Comment by tibtab** [comment]
hm maybe it isn't implemented in the prereleases of mozfr?

**Comment by tibtab** [comment]
sorry, now I see that I can send details, but only one number

**Pull request merged**
