### PR TITLE
german translation

### PR DESCRIPTION
**Pull request by markuman**
german translation is ~95% done.
i just don't know what's exactly the meaning of "PresenceStart=Starting presence" and alle the "Bolt" stuff.

### CODE REVIEW

**Comment by aesedepece** [comment]
"Starting presence" means that the app is sending "connected" status to your contacts.

With "Bolt" we mean "thunder". It's like a "buzz" in Yahoo Messenger.

THANKS A LOT!

**Comment by aesedepece** [comment]
For convenience, you can use our translation platform at http://translate.loqui.im

**Comment by markuman** [comment]
alright, i do.

**Comment by aesedepece** [comment]
When you are done with the translation in the platform and after revising it, please download it and pose a pull request so that your nice job is duly credited in GitHub. Thanks!

**Pull request merged**
