### PR TITLE
Change background

### PR DESCRIPTION
**Pull request by Gioyik**
@aesedepece Could you check why the background image is not changing correctly?

### CODE REVIEW

**Comment by aesedepece** [comment]
What's the issue itself?

**Comment by Gioyik** [comment]
The background is not changing.

**Comment by aesedepece** [comment]
What UI solution are you using at last? I've tried your branch and I can't find any option to change the background.

**Comment by Gioyik** [comment]
Como hago para capturar el largo y ancho de la imagen que pongo de fondo? Para el largo de la pantalla he usado window.innerHeight. Revisa el ultimo commit.

**Pull request merged**
