### PR TITLE
Voice Messages

### PR DESCRIPTION
**Pull request by TitanNano**
Voice message recorder implementation.   Works fine on Flame with FxOS 2.6
I would be glad if others could test it too before we deploy it.

NOTE: This doesn't assure that the receiver is able to actually open our voice message. I think android is able to decode ogg, but I'm not sure about other platforms.

### CODE REVIEW

**Comment by cmeerw** [comment]
Not sure how it's supposed to work...

Click on the microphone and it starts recording, swipe left and it stops recording. Click on the microphone again and it now uploads the previous recording and starts recording again.

**Comment by cmeerw** [comment]
BTW, the "swipe left ..." text needs the l10n magic

**Comment by TitanNano** [comment]
hold to record, release to send, swipe to abort

Yes you are right. I will land an other patch with l10n and feature
detection so the mic doesn't show up for XMPP.

2016-01-05 20:00 GMT+01:00 Christof Meerwald notifications@github.com:

**Comment by cmeerw** [comment]
Hmm ok, but a permissions dialog then completely screws up the hold/release part... (maybe another click on the icon should also stop/send the recording - in case the "release" event got lost)

And it appears that a swipe left doesn't always throw away the recording (but it sometimes gets uploaded when trying to record again).

**Comment by ElPopi** [comment]
I'm having the same issue 

> a permissions dialog then completely screws up the hold/release part...

 on a ZTE openII (ffoxOS v1.3). Is not possible to send a whatsapp voice message at all, because of that dialog. 

Any clue?

**Comment by TitanNano** [comment]
@ElPopi after you approved the permission you should be able to record your message. The Dialog shows up only once.

**Comment by ElPopi** [comment]
Thanks, TitanNano. But unfortunatelly EACH time I tap/hold on record button this dialogue shows up, and has not a "remember" checkbox as in other permission dialog messages like "share location".

**Comment by TitanNano** [comment]
@ElPopi which version of Firefox OS are you using?

**Comment by ElPopi** [comment]
@TitanNano 1.3, still the latest official release from ZTE

**Comment by bryanjhv** [comment]
Same thing like @ElPopi here. Using Firefox OS 1.3 on Alcatel OneTouch Fire C. It seems this release specially don't save the microphone permission, while 1.4+ do.

**Pull request merged**
