### PR TITLE
Switch to libphonenumber.js

### PR DESCRIPTION
**Pull request by aesedepece**
This potentially fixes many issues.

_Testing procedure_
Open the WhatsApp account on foreground, go to Contacts tab and run this on App Manager:

```
Messenger.account().core.roster = [];
Messenger.account().save();
Messenger.account().allRender();
```

Then tap the sync button and see if your contacts reappear and you can see their avatars and statuses.

### CODE REVIEW

**Comment by Gioyik** [comment]
The contacts and the button are working now. But the avatar and status are not displayed.

**Comment by aesedepece** [comment]
I mean, if you go into a chat, it loads the avatar and availability status just like it always did ;)

**Comment by aesedepece** [comment]
Although most avatars should reappear without having to go into the chats because the JIDs haven't changed.

**Comment by Gioyik** [comment]
To me are not showed. Also, the messages duplicate the chats with this commit.

**Comment by aesedepece** [comment]
So weird... this PR doesn't modify a single line in chats.js, so I can't understand how that happened. 

Everything fine for me on Peak with B2G1.4. What's yours?

**Comment by Gioyik** [comment]
Don't worry about duplicated chats, was my fault. Now the problem that i am seeing is avatar image is not loaded with this PR.

**Comment by aesedepece** [comment]
@Gioyik You can't see avatars only with WhatsApp accounts, or with any provider?

**Comment by aesedepece** [comment]
Please check that you are in the correct branch `git@github.com:aesedepece/loqui.git switch-to-libphonenumber`.

If your avatars are still missing, I'd try this:

```
App.avatars = [];
App.smartupdate('avatars', function(){Messenger.account().allRender()});
```

Then go into a chat and the avatar should be loaded properly.

**Comment by Gioyik** [comment]
@aesedepece  One question, if i receive a message from a contact that i don't have added to my contact list, it should show the profile image of this contact?

**Comment by aesedepece** [comment]
Yes, it should.

**Comment by Gioyik** [comment]
OK, this is the behavior.

I receive a message from 2 different contacts that i don't have on my contact list. The avatar is not showed but the status yes.

That's the unique problem because the others that I mentioned are resolved, probably my fault.

Regards,
Gio

**Comment by aesedepece** [comment]
Do you know if they even have an avatar at all?

You can check with this code:

```
Messenger.account().connector.events.onAvatar = console.log;
Messenger.account().connector.avatar(console.log, 'INTNUMBER@s.whatsapp.net');
```

It should answer:

```
"Received socket data: 1448 bytes! ~ BinaryReader.prototype.onSocketData@app://ea0c9e6f-0271-49fa-92af-7e284e648f7d/scripts/anonymous/coseme.js:4557 [BinaryReader]"
[...]
"<iq from="INTNUMBER@s.whatsapp.net" id="get_picture_14" type="result">
<picture xmlns="w:profile:picture" id="1370197013" type="image">
ÿØÿà [...]
"INTNUMBER@s.whatsapp.net" 1370197013 Blob {size: 21163, type: "image/jpeg"}
```

If the contact has no avatar or it's not registered to WhatsApp, the answer should be:

```
"<iq from="INTNUMBER@s.whatsapp.net" id="get_picture_17" type="error">
<error code="404" text="item-not-found">
</error>
</iq>
 ~ BinaryReader.prototype._readNextTree@app://ea0c9e6f-0271-49fa-92af-7e284e648f7d/scripts/anonymous/coseme.js:4656 [BinaryReader]"
```

_If you run the commands in this message, remember to restart the app after you finish to restore all event handlers._

**Comment by aesedepece** [comment]
The "avatar not showed" issue happened today once to me, but I restarted the app and it worked as usual.

**Comment by pavi** [comment]
@aesedepece Thank you :) , this is quite a newbie question , but how can I test this one from ZTE 1.1 ? Is there a way to do it ?

**Comment by jorgeuve** [comment]
Download and  unzip the last zip from github. Put your device in debug mode. Install firefox simulator on your firefox brownser and plug your zte. (open under tools-> development) Your device must appear and you can brownse for the manifest file in the directory you have downloaded.

**Comment by Gioyik** [comment]
I am not sure why but the unique way to get the avatar of a person is opening the chat first from the contact list. If I receive a message from a contact that i don't have in my contact list I couldn't get his profile picture and the contact has one.

We can merge this and let users test and see if this only happens to me, what you think @aesedepece?

**Comment by aesedepece** [comment]
I agree let's see if this works for early adopters. Merging!

**Pull request merged**
