### PR TITLE
Fix for Could not sent SMS

### PR DESCRIPTION
**Pull request by gargsms**

### CODE REVIEW

**Comment by gargsms** [comment]
@aesedepece Done. Merge it. Thanks.

**Comment by sergioad** [comment]
@gargsms when will land on the Firefox Marketplace this fix?

**Comment by gargsms** [comment]
That is not something I can do. @aesedepece Is the app updated on Marketplace?

**Comment by sergioad** [comment]
@aesedepece please upload this fix to the Marketplace, I am with not WhatsApp and this is so sad :cry:

**Comment by gargsms** [comment]
@sergioad Did you try the fix yet?

I never got any SMS. My new Loqui installation somehow just works after the SMS sent message.

**Comment by sergioad** [comment]
Nope how can I try it; as I said it is not a loqui reinstallation in my case, I have upgraded my Firefox OS to the new 2.1 build and shurelly I will keep updating it constantlly so I will need this fix as fast as posible

**Comment by gargsms** [comment]
@sergioad All you need to do is to download this repo, make a new folder somewhere, lets say 'test', and then copy the contents of src folder and the manifest.webapp file in 'test'.

Now you can connect your phone for debugging to your PC, start Firefox or Nightly or Dev Edition, and open the WebIDE. In the WebIDE, you can navigate to your folder using Open Packaged App. Once you have done that, you will see Loqui appearing in the centre pane.
If you have selected your phone as the runtime, you can simply press the start button on the top. That would install this version in your phone.

Help on WebIDE is here: https://developer.mozilla.org/en-US/docs/Tools/WebIDE

**Comment by sergioad** [comment]
Ok

**Comment by gargsms** [comment]
Wow! That was terse. Anyway, please tell us if this worked.

**Comment by sergioad** [comment]
Ok I will give it a try but this will unlink my actual Loqui app from the store updates?

**Comment by gargsms** [comment]
I guess this is the best you can do for the time being. And if you install a new version from the Marketplace later, I guess that will just overwrite this installation. 

I am using testing builds of IM for feature additions and not from the Marketplace. I should say that I haven't experienced any shortcomings whatsoever.

Moreover, I am not very sure if there is an option for automatic update of the apps as of now in Firefox OS. I haven't been active at all in that area.

**Comment by sergioad** [comment]
I see, I will wait for the oficial update friend

**Comment by willyaranda** [comment]
Hey guys, I would love to have this change pushed on the upstream code ;)

I fixed this 7 days ago: https://github.com/mozillahispano/coseme/commit/d63cc5f9478a7c0467cc38b03ceffade86c0f1b9

BTW: that is the official repo of the CoSeMe library

**Pull request merged**
