### PR TITLE
Change to emojione emojis

### PR DESCRIPTION
**Pull request by Honk2**
The WhatsApp Emojis are now taken from emoji one, increased in number and the input div looks more like the original including categories and backspace button.

### CODE REVIEW

**Comment by cmeerw** [comment]
I don't really have an opinion about emojis... BTW, is it a true super set of the old set of emojis or a different set of emojis?

Making it look like another application is not necessarily a good thing.

**Comment by tibtab** [comment]
I don't konw if it has something to do with this, but there are a few emojis, which are not displayed to me. Where they should be are only little squares.

**Comment by Honk2** [comment]
The reason I did it, was that the old set supported 800+ emojis and WhatsApp after the last update about 1600+. Since then I received many messages where I could only see grey boxes. This is when others us the new emojis.

Why EmojiOne?
The old implementation looked to me as manual import of the android or other sources. That means, everytime the is an update, it is maual work to include the new icons. Also I did not find the sources. With EmojiOne you simply download the new sources and are done. Also EmojiOne seems to be verey close (in regards of the number of images, see emojipedia) to the Apple Emoji set, which is used by WhatsApp and I guess it will also get updates more frequently.

To cut the matter short: If you are communicating with WhatssApp contacts some may like to see all the emojis used by others and like to use the new emojis available.

@cmeerw There are more than 1600 emojis in the current implementation. The old small single window looks quite unpractical to me. Also if you tap the wrong emoji, it is more convinient to have a backspace without changing back to the keyboard. Of cause, there is no need to copy the look of another application, but I do not any better ideas and am not stick to this layout. But this categories are kind of agreed  standard across web pages and applications.

@titab The grey boxes only appear in the text input field. This is because the Noto-Font installed to the device does not support the new emojis. This behaviour is like before, in the text field a font is used to display emojis, in the chat images are used. By now I did not get another font to work in the text field but will continue to look for a solution. Before display, the message text is parsed by connectors fy() function and the unicode characters are replaced by their images (as before).

**Comment by Honk2** [comment]
to be more technical:
Emojis are standarized in the unicode character set. Actual Standard supported by most Apps and systems is version 8. The old emojis are compatible with vesion 6 or 7. EmojiOne ist compatible with Version 8 and probaply the only one that will be updated also to version 9 and 10 and is available under cc license and not involved with any other major player.

**Pull request merged**
