### PR TITLE
Fix #596

### LINKED ISSUE #596: [WhatsApp] Implement Voice call activation
There have been multiple issues regarding the activation code not being received.

Someone, please implement this. PLEASE.

### PR DESCRIPTION
**Pull request by aesedepece**

### CODE REVIEW

**Comment by aesedepece** [comment]
@gargsms This is dedicated to you :laughing:

**Comment by gargsms** [comment]
Didn't work for me. :sob: 
I even tried the SMS with the correct MCC and MNC.

None worked. I will see if it works with a new number.

**Comment by aesedepece** [comment]
Yup, I suppose your number has been blocked. 
Just to make sure, have you tried requesting SMS from Yowsup, WART, http://watools.es or http://wha.tools?

**Comment by gargsms** [comment]
Could not send SMS - Reason unknown. :imp:

**Pull request merged**
