### PR TITLE
add-decrypt-error-msg

### PR DESCRIPTION
**Pull request by Honk2**
in the chat where the error occurs. this will help to regocnize any errors without reading the logs.

### CODE REVIEW

**Comment by cmeerw** [comment]
I believe this could have unintended side effects in that a "delivered" and even a "viewed" ack will be sent to the sender...

Ideally, a proper fix would also fix #1080.

So what we could do is:
- display a message that decryption failed (but this shouldn't generate any "delivered"/"viewed" acks)
- when the retry succeeds and we already have a message with a particular message id, we replace that message (and now send the acks) - and any duplicate message received will not show up twice.

**Comment by Honk2** [comment]
Your comment sounds reasonable. I will try.

**Comment by cmeerw** [comment]
I have actually had a go at this in #1114 - there might be a few bugs left though...

**Comment by Honk2** [comment]
This really great. Thank you.

**Pull request closed without merging**
