### PR TITLE
Update to WA 2.11.453

### PR DESCRIPTION
**Pull request by aesedepece**

### CODE REVIEW

**Comment by aesedepece** [comment]
r?
@gargsms Test to send SMS with this version. Thanks!

**Comment by gargsms** [comment]
I can't test it. I need to wait another 44 hours. :(

**Comment by aesedepece** [comment]
You can try to send activation SMS to friends and relatives and ask them to report to you if they receive something and then forget about the message. I'm doing so all the time :laughing:

**Comment by gargsms** [comment]
We must implement the voice call activation as well. I am raising an issue.

**Comment by gargsms** [comment]
The official WhatsAPI repository is a treasure trove of information about the working of WhatsApp.

Sadly I have exams scheduled this week. I will try to solve this awful registration issue this weekend, once and for all.

**Comment by aesedepece** [comment]
@gargsms I finally received the code via "voice" instead of "sms"

**Comment by gargsms** [comment]
I tried using 'voice' from AppManager console by firing CoSeMe.http.doRequest([parameters])
The attempt failed and now I need to wait another 30 minutes. Dang. :disappointed: 

Implement the voice activation ASAP. The method we adopted is not at all accessible to non-developer users. It should be easy IMO.

**Comment by gargsms** [comment]
'voice' activation too didn't work for me. :sob:

**Pull request merged**
